[
{
    "id":"1",
    "nama":"Dream House",
    "alamat":"Jl. Kedung Asem 121",
    "harga/bulan":800000,
    "harga/minggu":500000,
    "picture":"https://swamediainc.storage.googleapis.com/swa.co.id/wp-content/uploads/2022/07/29174023/kost.jpg",
    "fasilitas":"Kasur, lemari, meja",
    "type_kost":"Wanita",
    "bawa_hewan":"Boleh",
    "deskripsi":"Kost murah dan nyaman, dengan kawasan yang strategis",
    "email":"dreamhouse@gmail.com",
    "phone_number":"081475165849",
    "jumlah_kamar":20,
    "kamar_terisi":14
},{
    "id":"2",
    "nama":"Cozy Corner",
    "alamat":"Jl. Rungkut Mejoyo Utara 11",
    "harga/bulan":600000,
    "harga/minggu":400000,
    "picture":"https://binabangunbangsa.com/wp-content/uploads/2020/03/tips-Manajemen-Rumah-Kost-yang-Baik-dan-Benar-.jpg",
    "fasilitas":"Kasur, TV, meja, kamar mandi luar",
    "type_kost":"Pria",
    "bawa_hewan":"Tidak",
    "deskripsi":"Kost dekat ubaya",
    "email":"cozycorner@gmail.com",
    "phone_number":"08978451647",
    "jumlah_kamar":12,
    "kamar_terisi":10
},{
    "id":"3",
    "nama":"Artistic Abode",
    "alamat":"Jl. Tenggilis Kauman 2",
    "harga/bulan":650000,
    "harga/minggu":400000,
    "picture":"https://cf.bstatic.com/xdata/images/hotel/max1024x768/275364746.jpg?k=bee2233bb1e094152b8b70e6bcbfb92029f252feb89cc80290f86bb748a2cfd9&o=&hp=1",
    "fasilitas":"Kasur, wifi, meja, kamar mandi dalam",
    "type_kost":"Wanita",
    "bawa_hewan":"Boleh",
    "deskripsi":"Kost harga terjangkau dengan fasilitas lengkap",
    "email":"artisticabode@gmail.com",
    "phone_number":"087842184684",
    "jumlah_kamar":16,
    "kamar_terisi":11
},{
    "id":"4",
    "nama":"The Pastel Palace",
    "alamat":"Jl. Nginden Barat 31",
    "harga/bulan":875000,
    "harga/minggu":600000,
    "picture":"https://www.rukita.co/stories/wp-content/uploads/2021/10/kost-rukita-di-jakarta-selatan-dengan-jendela.jpg",
    "fasilitas":"Kasur, meja, kursi, kamar mandi dalam",
    "type_kost":"Wanita",
    "bawa_hewan":"Boleh",
    "deskripsi":"Kost dengan fasilitas lengkap dan di kawasan elite",
    "email":"pastelpalace@gmail.com",
    "phone_number":"081975426845",
    "jumlah_kamar":14,
    "kamar_terisi":8
},{
    "id":"5",
    "nama":"The Garden Room",
    "alamat":"Jl. Mejoyo Indah 133",
    "harga/bulan":1200000,
    "harga/minggu":800000,
    "picture":"https://cdn.rukita.co/rukita/fit/800x500/media/buildings/building/98ffd4c9-a7b.jpg",
    "fasilitas":"Kasur, wifi, AC, lemari, meja, kamar mandi dalam",
    "type_kost":"Wanita",
    "bawa_hewan":"Tidak",
    "deskripsi":"Kost dekat dengan Ubaya dan Transmart Rungkut",
    "email":"gardenroom@gmail.com",
    "phone_number":"0821478564982",
    "jumlah_kamar":15,
    "kamar_terisi":13
},{
    "id":"6",
    "nama":"The Bohemian House",
    "alamat":"Jl. Jemursari Regency AA 26",
    "harga/bulan":900000,
    "harga/minggu":650000,
    "picture":"https://apollo-singapore.akamaized.net/v1/files/hyfy5cjige4n2-ID/image;s=850x0",
    "fasilitas":"Kasur, meja, kamar mandi luar",
    "type_kost":"Pria",
    "bawa_hewan":"Tidak",
    "deskripsi":"Kost dengan lingkungan yang asri",
    "email":"bohmianhouse@gmail.com",
    "phone_number":"087779825141",
    "jumlah_kamar":10,
    "kamar_terisi":6
},{
    "id":"7",
    "nama":"The Retro Residence",
    "alamat":"Jl. Panjang Jiwo Permai 25",
    "harga/bulan":700000,
    "harga/minggu":500000,
    "picture":"https://cdn1-production-images-kly.akamaized.net/bRlJWmcbisPKVhH1vxjr0d5bUQs=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/861628/original/073424800_1429960385-3.JPG",
    "fasilitas":"Kasur, wifi, kamar mandi luar",
    "type_kost":"Pria",
    "bawa_hewan":"Tidak",
    "deskripsi":"Kost murah dan harga terjangkau",
    "email":"retroresidence@gmail.com",
    "phone_number":"08298871682",
    "jumlah_kamar":8,
    "kamar_terisi":3
},{
    "id":"8",
    "nama":"The Minimalist Loft",
    "alamat":"Jl. Tenggilis Utara 214",
    "harga/bulan":800000,
    "harga/minggu":550000,
    "picture":"https://blog-images.reddoorz.com/uploads/image/file/9920/rumah-kost-koolkost-near-university-of-indonesia.jpg",
    "fasilitas":"Kasur, meja, kursi",
    "type_kost":"Wanita",
    "bawa_hewan":"Tidak",
    "deskripsi":"Kost dengan jaminan fasilitas sangat nyaman",
    "email":"minimalistloft@gmail.com",
    "phone_number":"084974984981",
    "jumlah_kamar":14,
    "kamar_terisi":9
},{
    "id":"9",
    "nama":"The Green House",
    "alamat":"Jl. Rungkut Industri II",
    "harga/bulan":1000000,
    "harga/minggu":750000,
    "picture":"https://tempat-kost.com/images1/1499_2.jpg",
    "fasilitas":"Kasur, AC, meja, kamar mandi dalam",
    "type_kost":"Pria",
    "bawa_hewan":"Tidak",
    "deskripsi":"Kost baru dan eksklusif di kawasan yang strategis",
    "email":"greenhouse@gmail.com",
    "phone_number":"082134851654",
    "jumlah_kamar":6,
    "kamar_terisi":5
},{
    "id":"10",
    "nama":"The Scandinavian Suite",
    "alamat":"Jl. Rungkut Mejoyo A 21",
    "harga/bulan":900000,
    "harga/minggu":500000,
    "picture":"https://cdn.rukita.co/rukita/fit/800x500/media/buildings/building/1866e227-8df.jpg",
    "fasilitas":"Kasur, wifi, meja, lemari",
    "type_kost":"Wanita",
    "bawa_hewan":"Boleh",
    "deskripsi":"Kost dekat ubaya hanya butuh 5 Menit!",
    "email":"scandinaviansuite@gmail.com",
    "phone_number":"089412577564",
    "jumlah_kamar":13,
    "kamar_terisi":11
},{
    "id":"11",
    "nama":"The Sunny Side",
    "alamat":"Jl. Tenggilis Raya 131",
    "harga/bulan":1450000,
    "harga/minggu":1000000,
    "picture":"https://apollo-singapore.akamaized.net/v1/files/5ehffab7nx4o3-ID/image;s=850x0",
    "fasilitas":"Kasur, wifi, meja, lemari, AC, kamar mandi dalam, TV",
    "type_kost":"Wanita",
    "bawa_hewan":"Boleh",
    "deskripsi":"Kost luas dengan fasilitas super lengkap",
    "email":"sunnyside@gmail.com",
    "phone_number":"087461564497",
    "jumlah_kamar":7,
    "kamar_terisi":5
},{
    "id":"12",
    "nama":"The Blue Lagoon",
    "alamat":"Jl. Mejoyo 94",
    "harga/bulan":600000,
    "harga/minggu":450000,
    "picture":"https://idkos.com/images/gallery_property/standar-17.jpeg",
    "fasilitas":"Kasur, kamar mandi dalam",
    "type_kost":"Pria",
    "bawa_hewan":"Tidak",
    "deskripsi":"Kost murah dan kawasan yang strategis",
    "email":"bluelaogon@gmail.com",
    "phone_number":"08124658794",
    "jumlah_kamar":16,
    "kamar_terisi":10
}
]